### ISSUE TITLE
Remove source when renaming orignal file.

### ISSUE THREAD

**Issue by wiredmax** [webpack/compression-webpack-plugin#11]
Would you be open to this idea if I submit a PR that allow you to delete the source of a file once it's gzipped if the result file name is different than the original with an augument like `removeOriginal: true`?

We have a case where we only want to keep only the gizped version in gzip folder. `asset: "gzip/{file}"`. We currently do that using a custom plugin exectued right after the compression, but it may be an option that some other people might be interested into having.

**Comment by sokra** [comment]
yes, you can submit a PR.

**Comment by palmerj3** [comment]
Closing since this is not an issue
