### ISSUE TITLE
Compression Level option (or hardcode to 9)

### ISSUE THREAD

**Issue by Parakleta** [webpack/compression-webpack-plugin#12]
Since ideally this should be part of a build chain that compresses once and then delivers many times (as opposed to live compression) it makes sense to use the highest possible compression level.

Can you please either add an option to specify, or else change the default to use level 9 instead of the zlib default of 6.

**Comment by bfin** [comment]
Was looking to do the same thing. While I agree it'd be a useful option, @sokra has a lot on his plate. This is my workaround:

First, define your algorithm...
```js
var zlib = require('zlib');
function gzipMaxCompression(buffer, callback) {
  return zlib['gzip'](buffer, {level: 9}, callback)
}
```

...then pass to `CompressionPlugin`
```js
new CompressionPlugin({
    algorithm: gzipMaxCompression
})
```

**Comment by Parakleta** [comment]
@bfin thanks very much, this workaround is exactly what I needed.  I completely missed that you could pass in a function as the algorithm.

**Comment by D1plo1d** [comment]
I've put in a pull request to add level as an option and set it by default to 9. Hopefully this can get merged in: https://github.com/webpack/compression-webpack-plugin/pull/13

**Comment by chaddjohnson** [comment]
Doesn't work anymore. I get

```
zlib.js:130
    callback(err, responseData(engine, buf));
    ^

TypeError: callback is not a function
    at Gzip.onEnd (zlib.js:130:5)
    at emitNone (events.js:110:20)
    at Gzip.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
