### ISSUE TITLE
Unexpected character added to &nbsp

### ISSUE THREAD

**Issue by richtier** [webpack/compression-webpack-plugin#20]
When compressor is active I get the following:

<img width="239" alt="screen shot 2016-02-28 at 01 12 12" src="https://cloud.githubusercontent.com/assets/5485798/13376610/56fcf1a6-ddb8-11e5-83c6-3ec4e18a8932.png">

The `Â` should not be there. It is not there when compressor is not active.

my config is as follows:

```js
    new CompressionPlugin({
      asset: '{file}.gz',
      test: /\.js$|\.jpg$/,
      threshold: 10240,
      minRatio: 0.8
    })
```

**Comment by richtier** [comment]
spoke too soon - was this problem: https://github.com/callemall/material-ui/issues/2244

**Comment by StokeMasterJack** [comment]
I am getting the exact same problem. But I am not using callemall/material-ui#2244. I think it may have something to do with charsets.

**Comment by tommymcglynn** [comment]
Adding this to my html <head> resolved the issue for me.

    <meta http-equiv="content-type" content="text/html; charset=utf-8">

**Comment by JanM95** [comment]
@tommymcglynn worked for me too, thanks for posting!
