### ISSUE TITLE
Assets generated by extract-text-webpack-plugin are not compressed

### ISSUE THREAD

**Issue by romeovs** [webpack/compression-webpack-plugin#22]
The assets that are created by `extract-text-webpack-plugin` are not compressed in my web pack builds.

For instance `.css` files are not compressed. The funny thing is that the `.css.map` files *are* compressed.

Has anyone noticed this?
I will post a configuration example tomorrow!

**Comment by romeovs** [comment]
This is my config:
```
var Compression = require('compression-webpack-plugin')
var Extract     = require('extract-text-webpack-plugin')

var path = require('path')

module.exports = {
  context: path.resolve(__dirname)
, entry: {
    main: [
      './src/index.js'
    , './src/style.css'
    ]
  }
, output: {
    path: path.resolve(__dirname, 'assets')
  , filename: '[name].[hash].js'
  }
, module: {
    loaders: [
      {
        test: /\.css$/
      , loader: 'extract-text-webpack-plugin/loader?extract&remove!css'
      }
    ]
  }
, plugins: [
    new Extract('[name].[hash].css', {
      allChunks: true
    })
  , new Compression({
      asset: '{file}.gz'
    , algorithm: 'gzip'
    })
  ]
}
```

**Comment by romeovs** [comment]
OK. Let's just say I was tired yesterday. It turns out the css file wasn't gzipped because the ratio wasn't good enough.

**Comment by cj** [comment]
@romeovs what settings did you use to get it to work and gzip the css?

**Comment by romeovs** [comment]
You should make sure that the CSS file is large enough for it to be compressed significantly enough for the compression to make sense (otherwise the browser will spend more time unzipping the file than in just receiving it uncompressed). 

This is expressed using the `ratio` option, it defaults to `.8` from what I can see. This means that the compressed file should have at most 0.8 times the size of the original file.

Because for really small files, the gzipped one can even be (much) larger than the original, setting the `ratio` to 1 is not enough. I set it to 4, but to make sure it really *always* works, you could set it to `Infinity`. 

Hope this helps!

*Typed on my smartphone, so will contain errors.*
