### ISSUE TITLE
Error "Algorithm not found in zlib"

### ISSUE THREAD

**Issue by danb-cws** [webpack/compression-webpack-plugin#28]
EDIT: working now, replaced: algorithm: 'gzipMaxCompression', with just gzip. Not sure where I piced up that config. Thanks.

Trying to use this plugin on Windows and getting the error: "Algorithm not found in zlib"

node_modules\compression-webpack-plugin\index.js:36
if(!this.algorithm) throw new Error("Algorithm not found in zlib");

I'm on Windows10 pro and have followed the setup as per 
https://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64
... ie install VS, Python, added environment variables
This got rid of the previous errors with node-gyp, but now getting this new error.

**Comment by bmsdave** [comment]
@danb-cws  why close? you fix it?

**Comment by danb-cws** [comment]
@bmsdave I ended up using this package due to other issues
https://www.npmjs.com/package/compression

**Comment by manoj-makkuboy** [comment]
node version v12.2.0 fixes this

**Comment by anujm249** [comment]
Also working for v10.16.0
